# Generated by Django 4.1.5 on 2023-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0007_lab_lab_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="lab_id",
            field=models.AutoField(default="1", primary_key=True, serialize=False),
        ),
    ]
