# Generated by Django 4.1.5 on 2023-02-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0010_student_survey_student_id_alter_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-05 15:36:08Z"),
        ),
        migrations.CreateModel(
            name="response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_response",
                        to="db.student_lab_risk",
                    ),
                ),
                (
                    "y",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="y_response",
                        to="db.student_lab_risk",
                    ),
                ),
            ],
        ),
    ]
