# Generated by Django 4.1.5 on 2023-02-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0011_alter_message_sent_at_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="question_1_x",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question_1_y",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question_2_x",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question_2_y",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question_3_x",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question_3_y",
        ),
        migrations.AddField(
            model_name="survey",
            name="question_1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_1",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="question_2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_2",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="question_3",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_3",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-05 15:38:45Z"),
        ),
    ]
