# Generated by Django 4.1.5 on 2023-02-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0012_remove_survey_question_1_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_survey",
            name="response_1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="q_1",
                to="db.response",
            ),
        ),
        migrations.AddField(
            model_name="student_survey",
            name="response_2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="q_2",
                to="db.response",
            ),
        ),
        migrations.AddField(
            model_name="student_survey",
            name="response_3",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="q_3",
                to="db.response",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-05 15:40:42Z"),
        ),
    ]
