# Generated by Django 4.1.5 on 2023-02-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0014_lab_help_alter_message_sent_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_survey",
            name="response_1",
        ),
        migrations.RemoveField(
            model_name="student_survey",
            name="response_2",
        ),
        migrations.RemoveField(
            model_name="student_survey",
            name="response_3",
        ),
        migrations.AddField(
            model_name="student_survey",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student_survey",
            name="lab_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-07 19:38:22Z"),
        ),
    ]
