# Generated by Django 4.1.5 on 2023-02-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0019_average_response_alter_axis_labels_avg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="axis_average",
            name="student_id",
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.CASCADE, to="db.student"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-18 17:47:05Z"),
        ),
        migrations.DeleteModel(
            name="average_response",
        ),
    ]
