# Generated by Django 4.1.5 on 2023-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0022_alter_message_sent_at_tutor_teaching"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor_teaching",
            old_name="student_id",
            new_name="tutor_id",
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-20 18:20:17Z"),
        ),
    ]
