# Generated by Django 4.1.5 on 2023-02-24 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0035_alter_lab_help_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="lab_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="related_lab",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 24, 10, 11, 34, 365318)
            ),
        ),
    ]
