# Generated by Django 4.1.5 on 2023-03-01 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0040_alter_axis_labels_neg_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_enroll",
            name="tutor_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.tutor_teaching",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 1, 18, 27, 29, 984012)
            ),
        ),
    ]
