# Generated by Django 4.1.5 on 2023-03-01 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0041_student_enroll_tutor_id_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 1, 18, 27, 46, 752602)
            ),
        ),
    ]
