# Generated by Django 4.1.5 on 2023-03-01 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0042_alter_message_sent_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student_enroll",
            old_name="lab_id",
            new_name="course_id",
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 1, 18, 51, 22, 981565)
            ),
        ),
    ]
