# Generated by Django 4.1.5 on 2023-03-01 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0043_rename_lab_id_student_enroll_course_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_enroll",
            name="tutor_id",
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 1, 18, 56, 38, 619183)
            ),
        ),
        migrations.CreateModel(
            name="student_lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.lab"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.student"
                    ),
                ),
                (
                    "tutor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.tutor_teaching",
                    ),
                ),
            ],
        ),
    ]
