# Generated by Django 4.1.5 on 2023-01-08 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="axis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="axis_labels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos_title", models.CharField(max_length=20)),
                ("neg_title", models.CharField(max_length=20)),
                ("risk", models.IntegerField()),
                ("warn", models.IntegerField()),
                ("avg", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=20)),
                ("level", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="db",
            fields=[
                ("fname", models.CharField(default="John", max_length=30)),
                ("sname", models.CharField(default="Smith", max_length=30)),
                (
                    "email",
                    models.CharField(
                        default="johnsmith@mail.com",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(default="password", max_length=20)),
                ("staff", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="lab",
            fields=[
                (
                    "lab_id",
                    models.CharField(
                        default="1", max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        default="2444030s",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="tutor",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        default="2444030s",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student_lab_risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("risk", models.BooleanField()),
                ("warning", models.BooleanField()),
                ("avg", models.BooleanField()),
                (
                    "axis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.axis"
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.lab"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student_enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.course"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField()),
                ("message_content", models.TextField()),
                (
                    "receiver_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="axis",
            name="lab_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AddField(
            model_name="axis",
            name="x_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="x_id",
                to="db.axis_labels",
            ),
        ),
        migrations.AddField(
            model_name="axis",
            name="y_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="y_id",
                to="db.axis_labels",
            ),
        ),
    ]
