# Generated by Django 4.1.5 on 2023-01-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_lab_lab_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="title",
            field=models.CharField(default="", max_length=20),
        ),
    ]
