# Generated by Django 4.1.5 on 2023-02-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0008_alter_lab_lab_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-05 15:20:32Z"),
        ),
        migrations.AlterField(
            model_name="student_lab_risk",
            name="axis_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.axis_labels"
            ),
        ),
        migrations.CreateModel(
            name="student_survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.survey",
                    ),
                ),
            ],
        ),
    ]
