# Generated by Django 4.1.5 on 2023-02-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0013_student_survey_response_1_student_survey_response_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="help",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-07 17:03:15Z"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="question_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_1",
                to="db.question",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="question_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_2",
                to="db.question",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="question_3",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_3",
                to="db.question",
            ),
        ),
    ]
