# Generated by Django 4.1.5 on 2023-02-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0020_axis_average_student_id_alter_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="axis_average",
            name="above",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="axis_average",
            name="date",
            field=models.DateField(default="2022-02-02"),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-19 19:26:17Z"),
        ),
    ]
