# Generated by Django 4.1.5 on 2023-02-23 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0034_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="help",
            field=models.URLField(blank=True, default="blank.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 23, 20, 14, 38, 868608)
            ),
        ),
    ]
