# Generated by Django 4.1.5 on 2023-03-02 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0044_remove_student_enroll_tutor_id_alter_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 11, 54, 7, 807046)
            ),
        ),
    ]
