# Generated by Django 4.1.5 on 2023-03-08 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0050_alter_message_sent_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="db",
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 17, 22, 0, 120413)
            ),
        ),
        migrations.AlterField(
            model_name="student_survey",
            name="lab_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AlterField(
            model_name="student_survey",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.student"
            ),
        ),
        migrations.AlterField(
            model_name="student_survey",
            name="survey_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.survey"
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="lab_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="question_1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_1",
                to="db.question",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="question_2",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_2",
                to="db.question",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="question_3",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_3",
                to="db.question",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="tutor_teaching_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.tutor_teaching"
            ),
        ),
    ]
