# Generated by Django 4.1.5 on 2023-03-08 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0051_delete_db_alter_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 17, 28, 53, 648385)
            ),
        ),
    ]
