# Generated by Django 4.1.5 on 2023-03-08 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0052_alter_message_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_enroll",
            name="flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 17, 45, 29, 107500)
            ),
        ),
    ]
