# Generated by Django 4.1.5 on 2023-03-08 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0053_student_enroll_flag_alter_message_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="axis_labels",
            name="avg",
        ),
        migrations.AlterField(
            model_name="axis_labels",
            name="risk",
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name="axis_labels",
            name="warn",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 20, 36, 15, 863072)
            ),
        ),
    ]
