# Generated by Django 4.1.5 on 2023-03-11 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0055_remove_student_lab_risk_avg_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 11, 20, 50, 39, 599350)
            ),
        ),
    ]
