# Generated by Django 4.1.5 on 2023-03-11 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0056_alter_course_title_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 11, 20, 52, 19, 637019)
            ),
        ),
    ]
