# Generated by Django 4.1.5 on 2023-03-11 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0057_alter_course_id_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="title",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 11, 21, 5, 8, 241325)
            ),
        ),
    ]
