# Generated by Django 4.1.5 on 2023-03-14 20:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0058_alter_lab_title_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="axis_average",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 20, 7, 1, 795184)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tutor_teaching",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.course"
            ),
        ),
    ]
