# Generated by Django 4.1.5 on 2023-03-14 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0059_alter_axis_average_date_alter_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 20, 7, 8, 696478)
            ),
        ),
    ]
