# Generated by Django 4.1.5 on 2023-03-14 20:09

import datetime
import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0060_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 20, 9, 41, 483479)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=db.models.IntegerRangeField(),
        ),
    ]
