# Generated by Django 4.1.5 on 2023-03-14 20:21

import datetime
import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0061_alter_message_sent_at_alter_student_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="axis_average",
            name="point",
            field=db.models.IntegerRangeField(default=None),
        ),
        migrations.AlterField(
            model_name="axis_labels",
            name="risk",
            field=db.models.IntegerRangeField(default=9),
        ),
        migrations.AlterField(
            model_name="axis_labels",
            name="warn",
            field=db.models.IntegerRangeField(default=9),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=db.models.IntegerRangeField(default=None),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 20, 21, 15, 164227)
            ),
        ),
    ]
