# Generated by Django 4.1.5 on 2023-03-14 20:27

import datetime
import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0062_alter_axis_average_point_alter_axis_labels_risk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="lab_number",
            field=db.models.IntegerRangeField(default=None),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_content",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 20, 27, 58, 929787)
            ),
        ),
    ]
