# Generated by Django 4.1.5 on 2023-03-15 13:50

import datetime
import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0063_alter_lab_lab_number_alter_message_message_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="axis_labels",
            name="warn",
            field=db.models.IntegerRangeField(default=8),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 15, 13, 50, 8, 408123)
            ),
        ),
    ]
