# Generated by Django 4.1.5 on 2023-03-15 15:19

import datetime
import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0065_alter_message_sent_at_alter_student_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 15, 15, 19, 30, 381513)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=db.models.IntegerRangeField(default=None),
        ),
    ]
