# Generated by Django 4.1.5 on 2023-03-15 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0066_alter_message_sent_at_alter_student_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 15, 15, 54, 6, 202030)
            ),
        ),
    ]
