# Generated by Django 4.1.5 on 2023-03-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0068_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(),
        ),
    ]
