# Generated by Django 4.1.5 on 2023-01-06 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=20)),
                ("level", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="db",
            fields=[
                ("fname", models.CharField(default="John", max_length=30)),
                ("sname", models.CharField(default="Smith", max_length=30)),
                (
                    "email",
                    models.CharField(
                        default="johnsmith@mail.com",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(default="password", max_length=20)),
                ("staff", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        default="2444030s",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="tutor",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        default="2444030s",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
