# Generated by Django 4.1.5 on 2023-01-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="axis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="axis_labels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos_title", models.CharField(max_length=20)),
                ("neg_title", models.CharField(max_length=20)),
                ("risk", models.IntegerField()),
                ("warn", models.IntegerField()),
                ("avg", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="lab",
            fields=[
                (
                    "lab_id",
                    models.CharField(
                        default="1", max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student_lab_risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("risk", models.BooleanField()),
                ("warning", models.BooleanField()),
                ("avg", models.BooleanField()),
                (
                    "axis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.axis"
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.lab"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student_enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.course"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="axis",
            name="lab_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AddField(
            model_name="axis",
            name="x_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="x_id",
                to="db.axis_labels",
            ),
        ),
        migrations.AddField(
            model_name="axis",
            name="y_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="y_id",
                to="db.axis_labels",
            ),
        ),
    ]
