# Generated by Django 4.1.5 on 2023-01-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_remove_axis_lab_id_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="lab_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AlterField(
            model_name="lab",
            name="lab_id",
            field=models.IntegerField(default="1", primary_key=True, serialize=False),
        ),
    ]
