# Generated by Django 4.1.5 on 2023-01-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_survey_lab_id_alter_lab_lab_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="question_1",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question_2",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="question_3",
        ),
        migrations.AddField(
            model_name="survey",
            name="question_1_x",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_1_x",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="question_1_y",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_1_y",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="question_2_x",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_2_x",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="question_2_y",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_2_y",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="question_3_x",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_3_x",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="question_3_y",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_3_y",
                to="db.axis_labels",
            ),
            preserve_default=False,
        ),
    ]
