# Generated by Django 4.1.5 on 2023-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0006_remove_survey_question_1_remove_survey_question_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="lab_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
