# Generated by Django 4.1.5 on 2023-02-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0015_remove_student_survey_response_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-16 16:42:09Z"),
        ),
        migrations.CreateModel(
            name="axis_average",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.IntegerField()),
                (
                    "axis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.axis_labels"
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.lab"
                    ),
                ),
            ],
        ),
    ]
