# Generated by Django 4.1.5 on 2023-02-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0018_alter_message_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="average_response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("above", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="axis_labels",
            name="avg",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="axis_labels",
            name="risk",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="axis_labels",
            name="warn",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-18 17:05:30Z"),
        ),
        migrations.DeleteModel(
            name="response",
        ),
        migrations.AddField(
            model_name="average_response",
            name="axis_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.axis_labels"
            ),
        ),
        migrations.AddField(
            model_name="average_response",
            name="lab_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.lab"
            ),
        ),
        migrations.AddField(
            model_name="average_response",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.student"
            ),
        ),
    ]
