# Generated by Django 4.1.5 on 2023-02-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0021_axis_average_above_axis_average_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-20 18:01:21Z"),
        ),
        migrations.CreateModel(
            name="tutor_teaching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.lab"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.tutor"
                    ),
                ),
            ],
        ),
    ]
