# Generated by Django 4.1.5 on 2023-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0027_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default="2023-02-21 16:09:38Z"),
        ),
    ]
