# Generated by Django 4.1.5 on 2023-02-23 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0029_alter_message_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="related_lab",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.lab",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 23, 19, 13, 11, 259150)
            ),
        ),
    ]
