# Generated by Django 4.1.5 on 2023-02-23 19:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0030_message_related_lab_alter_message_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor_teaching",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 23, 19, 15, 26, 345383)
            ),
        ),
    ]
