# Generated by Django 4.1.5 on 2023-03-02 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0045_alter_message_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor_teaching",
            name="lab_id",
        ),
        migrations.RemoveField(
            model_name="tutor_teaching",
            name="user_id",
        ),
        migrations.AddField(
            model_name="tutor_teaching",
            name="course_id",
            field=models.ForeignKey(
                default="COMPSCI408",
                on_delete=django.db.models.deletion.CASCADE,
                to="db.course",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 11, 57, 48, 930030)
            ),
        ),
    ]
