# Generated by Django 4.1.5 on 2023-03-02 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0046_remove_tutor_teaching_lab_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_enroll",
            name="course_id",
        ),
        migrations.AddField(
            model_name="student_enroll",
            name="tutor_teaching_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.tutor_teaching",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 12, 0, 28, 466936)
            ),
        ),
    ]
