# Generated by Django 4.1.5 on 2023-03-02 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0047_remove_student_enroll_course_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="tutor_teaching_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.tutor_teaching",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 12, 3, 40, 733851)
            ),
        ),
    ]
