# Generated by Django 4.1.5 on 2023-03-02 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0048_survey_tutor_teaching_id_alter_message_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 12, 22, 1, 976794)
            ),
        ),
        migrations.DeleteModel(
            name="student_lab",
        ),
    ]
