# Generated by Django 4.1.5 on 2023-03-02 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0049_alter_message_sent_at_delete_student_lab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 21, 41, 18, 597689)
            ),
        ),
    ]
