# Generated by Django 4.1.5 on 2023-03-08 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0054_remove_axis_labels_avg_alter_axis_labels_risk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_lab_risk",
            name="avg",
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 8, 20, 37, 11, 611346)
            ),
        ),
    ]
